language: node_js
node_js:
 - "8"
cache: yarn
sudo: enabled
before_install:
 - sudo chmod +x ./install-dependencies.sh
install: sudo ./install-dependencies.sh
script: yarn test
after_success: cd server && yarn coverage